server:
  port: ${port}

spring:
  application:
    name: node01-eureka-register-7001

eureka:
  instance:
    hostname: 127.0.0.1
    # true\u5C06\u81EA\u5DF1\u7684ip\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D\u5FC3\u53BB
    prefer-ip-address: true
  client:
    # false\u8868\u793A\u4E0D\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1\uFF0C\u672C\u8EAB\u5C31\u662F\u6240\u6709\u65E0\u9700\u6CE8\u518C
    register-with-eureka: false
    # false\u8868\u793A\u8BE5\u7AEF\u5C31\u662F\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u65E0\u9700\u68C0\u7D22\u670D\u52A1\uFF0C\u7EF4\u62A4\u670D\u52A1\u5B9E\u4F8B\uFF0C\u4E0D\u53BB\u68C0\u7D22\u670D\u52A1
    fetch-registry: false
  service-url:
    # \u5355\u70B9\u6CE8\u518C\u4E2D\u5FC3
    # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # \u96C6\u7FA4\u6CE8\u518C\u4E2D\u5FC3
    defaultZone: ${eureka.server}

