server:
  port: 8001
spring:
  application:
    name: emp-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
