server:
  port: 9000

spring:
  application:
    name: emp-provider # 负载均衡，3个provider名称一致
    #数据源的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源为druid
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf-8&servetTimeZone=Asia/Shanghai
    username: root
    password: root

#mybatis配置
mybatis:
  type-aliases-package: com.zbs.com.zbs.springcloudeurekaprovider.db.mapper
  mapper-locations: classpath*:mapper/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      # 单机
      #defaultZone: http://eureka-server.com:8760/eureka
      # 集群
      defaultZone: http://eureka-server.com:8760/eureka,http://eureka-server-01.com:8761/eureka,http://eureka-server-02.com:8762/eureka
  instance:
    # 修改eureka上provider提供者的默认信息
    instance-id: springCloud-hystrix-provider-9000

# actuator info 监控台点击provider跳转页面信息
info:
  app.name: com.zbs.springcloud
  company.name: postGL，配置监控平台信息，标注自己是哪个服务
