server:
  port: 8081
spring:
  application:
    name: emp-customer
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
