server:
  port: 3344

# config demo：https://blog.csdn.net/qq_38863292/article/details/106566513
spring:
  application:
    name: springcloud-config-server
  # 连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zbsdemo/spring-cloud-config.git #是https，不是git
          username: *
          password: *
