server:
  port: 9000

spring:
  application:
    name: springCloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.com:8760/eureka,http://eureka-server-01.com:8761/eureka,http://eureka-server-02.com:8762/eureka
  instance:
    instance-id: springCloud-zuul-gateway-9000
    prefer-ip-address: true

info:
  app.name: zbs
  company.name: com.zbs

zuul:
  # *：所有项目都不能通过服务Id进行访问，必须通过配置进行访问
  # 不能在使用这个路径访问了，否则emp-provider和/mydept都可以进行访问
  ignored-services: "*"
  # 设置公共的前缀
  prefix: /zbs
  # /emp-provider会暴漏项目路径，用/mydept代替进行访问
  routes:
    mydept.serviceId: emp-provider
    mydept.path: /mydept/**
