server:
  port: 9000

spring:
  application:
    name: springCloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.com:8760/eureka,http://eureka-server-01.com:8761/eureka,http://eureka-server-02.com:8762/eureka
  instance:
    instance-id: springCloud-zuul-gateway-9000
    prefer-ip-address: true

info:
  app.name: zbs
  company.name: com.zbs
